=== Flexi-BLE/InterfaceModel/device.schema.json
{
    "$schema": "http://json-schema.org/draft-06/schema",
    "$ref": "#/definitions/FlexiBLEDevice",
    "definitions": {
        "FlexiBLEDevice": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "name": {
                    "title": "FlexiBLE Device Name",
                    "description": "A user friendly name for the FlexiBLE device",
                    "examples": ["ExampleSensor"],
                    "type": "string"
                },
                "description": {
                    "title": "FlexiBLE Device Description",
                    "description": "A user friendly description for the FlexiBLE device",
                    "examples": ["ExampleSensor is a sensor that does something"],
                    "type": "string"
                },
                "flexible_version": {
                    "const": "0.4.0",
                    "default": "0.4.0",
                    "type": "string",
                    "readOnly": true
                },
                "ble": {
                    "title": "BLE Details",
                    "description": "Details of the FlexiBLE device's BLE implementation",
                    "$ref": "#/definitions/FlexiBLEDeviceBle"
                },
                "config_values": {
                    "title": "Device Configurations",
                    "description": "Configuration values for the FlexiBLE device",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Value"
                    }
                },
                "commands": {
                    "title": "Device Commands",
                    "description": "Commands that can be initaited by the central ",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Command"
                    }
                },
                "data_streams": {
                    "title": "Data Streams",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/DataStream"
                    }
                }
            },
            "required": [
                "ble",
                "commands",
                "config_values",
                "data_streams",
                "description",
                "flexible_version",
                "name"
            ],
            "title": "FlexiBLEDevice"
        },
        "FlexiBLEDeviceBle": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "spec_services": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "info_service_uuid": {
                    "type": "string",
                    "format": "uuid"
                },
                "device_in_char_uuid": {
                    "type": "string",
                    "format": "uuid"
                },
                "device_out_char_uuid": {
                    "type": "string",
                    "format": "uuid"
                }
            },
            "required": [
                "device_in_char_uuid",
                "device_out_char_uuid",
                "info_service_uuid",
                "spec_services"
            ],
            "title": "FlexiBLEDeviceBle"
        },
        "Command": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "command_code": {
                    "type": "integer"
                },
                "app_requests": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/AppRequest"
                    }
                }
            },
            "required": [
                "app_requests",
                "command_code"
            ],
            "title": "Command"
        },
        "AppRequest": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "code": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "responses": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/AppRequest"
                    }
                },
                "response_type": {
                    "type": "string"
                }
            },
            "required": [
                "code",
                "description",
                "name"
            ],
            "title": "AppRequest"
        },
        "Value": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "name": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "index": {
                    "type": "integer"
                },
                "length": {
                    "type": "integer"
                },
                "unit": {
                    "anyOf": [
                        {
                            "type": "null"
                        },
                        {
                            "type": "string"
                        }
                    ]
                },
                "multiplier": {
                    "anyOf": [
                        {
                            "type": "number"
                        },
                        {
                            "type": "null"
                        }
                    ]
                },
                "data_type": {
                    "type": "string"
                },
                "selection_type": {
                    "anyOf": [
                        {
                            "type": "null"
                        },
                        {
                            "type": "string"
                        }
                    ]
                },
                "default_value": {
                    "$ref": "#/definitions/DefaultValue"
                },
                "options": {
                    "anyOf": [
                        {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/Option"
                            }
                        },
                        {
                            "type": "null"
                        }
                    ]
                },
                "range": {
                    "anyOf": [
                        {
                            "$ref": "#/definitions/Range"
                        },
                        {
                            "type": "null"
                        }
                    ]
                },
                "variable_type": {
                    "type": "string"
                },
                "depends_on": {
                    "type": "null"
                }
            },
            "required": [
                "data_type",
                "description",
                "index",
                "length",
                "multiplier",
                "name",
                "unit"
            ],
            "title": "Value"
        },
        "DefaultValue": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "data_type": {
                    "type": "string"
                },
                "value": {
                    "type": "string",
                    "format": "integer"
                }
            },
            "required": [
                "data_type",
                "value"
            ],
            "title": "DefaultValue"
        },
        "Option": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "name": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "value_int": {
                    "type": "integer"
                }
            },
            "required": [
                "description",
                "name",
                "value_int"
            ],
            "title": "Option"
        },
        "Range": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "start": {
                    "type": "number"
                },
                "end": {
                    "type": "number"
                },
                "step": {
                    "type": "number"
                }
            },
            "required": [
                "end",
                "start",
                "step"
            ],
            "title": "Range"
        },
        "DataStream": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "precision": {
                    "type": "string"
                },
                "config_values": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Value"
                    }
                },
                "data_values": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Value"
                    }
                },
                "ble": {
                    "$ref": "#/definitions/DataStreamBle"
                }
            },
            "required": [
                "ble",
                "config_values",
                "data_values",
                "description",
                "id",
                "name",
                "precision"
            ],
            "title": "DataStream"
        },
        "DataStreamBle": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "service_uuid": {
                    "type": "string",
                    "format": "uuid"
                },
                "data_char_uuid": {
                    "type": "string",
                    "format": "uuid"
                },
                "config_char_uuid": {
                    "type": "string",
                    "format": "uuid"
                }
            },
            "required": [
                "config_char_uuid",
                "data_char_uuid",
                "service_uuid"
            ],
            "title": "DataStreamBle"
        }
    }
}

=== Flexi-BLE/InterfaceModel/flexible-device.json
{
    "name": "flexible-example",
    "flexible_version": "0.4.0",
    "description": "an example flexible device used to generate the JSON schema",
    "ble": {
        "spec_services": [
            "battery",
            "device_information" 
        ],
        "info_service_uuid": "1a220001-c2ed-4d11-ad1e-fc06d8a02d37",
        "device_in_char_uuid": "1a220004-c2ed-4d11-ad1e-fc06d8a02d37",
        "device_out_char_uuid": "1a220005-c2ed-4d11-ad1e-fc06d8a02d37"
    },
    "config_values": [
        {
            "name": "_epoch",
            "description": "The epoch time (in seconds) used for the reference epoch time",
            "index": 0,
            "length": 8,
            "unit": "seconds",
            "multiplier": null,
            "data_type": "uint",
            "selection_type": null,
            "default_value": {
                "data_type": "int",
                "value": "0"
            }
        },
        {
            "name": "_epoch_reference",
            "description": "a reference point to unix epoch time, used to synchronize the device's time",
            "index": 1,
            "length": 8,
            "unit": "seconds",
            "multiplier": null,
            "data_type": "uint",
            "selection_type": null,
            "default_value": {
                "data_type": "int",
                "value": "0"
            }
        }
    ],
    "commands": [
        {
            "command_code": 0,
            "app_requests": [
                {
                    "code": 0,
                    "name": "reset",
                    "description": "force device software reset",
                    "responses": [
                        {
                            "code": 0,
                            "name": "acknowledge",
                            "response_type": "success",
                            "description": "device reset successfully"
                        },
                        {
                            "code": 1,
                            "name": "failure",
                            "description": "failed to reset device",
                            "response_type": "error"
                        }
                    ]
                }
            ]
        }
    ],
    "data_streams": [
        {
            "id": "accel",
            "name": "accelerometry",
            "description": "Accelerometer sensor (x, y, z axis)",
            "precision": "ms",
            "config_values": [
                {
                    "name": "sensor_state",
                    "description": "state of the accelerometer sensor",
                    "index": 0,
                    "length": 1,
                    "unit": null,
                    "multiplier": null,
                    "data_type": "uint",
                    "selection_type": "single",
                    "default_value": {
                        "data_type": "int",
                        "value": "0"
                    },
                    "options": [
                        {
                            "name": "disabled",
                            "description": "the sensor will not stream data",
                            "value_int": 0
                        },
                        {
                            "name": "streaming",
                            "description": "the sensor will stream data",
                            "value_int": 0
                        }
                    ],
                    "range": null
                },
                {
                    "name": "desired_frequency",
                    "description": "the desired frequency of the sensor",
                    "index": 1,
                    "length": 2,
                    "data_type": "uint",
                    "selection_type": "range",
                    "unit": "Hz",
                    "multiplier": null,
                    "options": null,
                    "default_value": {
                        "data_type": "int",
                        "value": "20"
                    },
                    "range": {
                        "start": 20.0,
                        "end": 500.0,
                        "step": 20.0
                    }
                },
                {
                    "name": "batch_size",
                    "description": "the maximun size of payload",
                    "index": 3,
                    "length": 1,
                    "data_type": "uint",
                    "selection_type": "range",
                    "unit": "bytes",
                    "options": null,
                    "multiplier": null,
                    "default_value": {
                        "data_type": "int",
                        "value": "240"
                    },
                    "range": {
                        "start": 0.0,
                        "end": 240.0,
                        "step": 10.0
                    }
                }
            ],
            "data_values": [
                {
                    "name": "accel_x",
                    "description": "x-axis value",
                    "unit": "ms/s^2",
                    "index": 0,
                    "length": 4,
                    "data_type": "int",
                    "multiplier": 0.000001,
                    "variable_type": "value",
                    "depends_on": null
                },
                {
                    "name": "accel_y",
                    "description": "y-axis value",
                    "unit": "ms/s^2",
                    "index": 4,
                    "length": 4,
                    "data_type": "int",
                    "multiplier": 0.000001,
                    "variable_type": "value",
                    "depends_on": null
                },
                {
                    "name": "accel_z",
                    "description": "z-axis value",
                    "unit": "m/s^2",
                    "index": 8,
                    "length": 4,
                    "data_type": "int",
                    "multiplier": 0.000001,
                    "variable_type": "value",
                    "depends_on": null
                },
                {
                    "name": "_offset",
                    "description": "relative time since the previous reading",
                    "unit": "ms",
                    "index": 5,
                    "length": 1,
                    "data_type": "uint",
                    "multiplier": null,
                    "variable_type": "offset",
                    "depends_on": null
                }
            ],
            "ble": {
                "service_uuid": "1a220003-c2ed-4d11-ad1e-fc06d8a02d37",
                "data_char_uuid": "1a220005-c2ed-4d11-ad1e-fc06d8a02d37",
                "config_char_uuid": "1a220004-c2ed-4d11-ad1e-fc06d8a02d37"
            }
        }
    ]
}
