=== Flexi-BLE/InterfaceModel/schema.json
{
    "$schema": "http://json-schema.org/draft-06/schema#",
    "$ref": "#/definitions/Welcome4",
    "definitions": {
        "Welcome4": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "id": {
                    "type": "string"
                },
                "schema_version": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string",
                    "format": "date-time"
                },
                "updated_at": {
                    "type": "string",
                    "format": "date-time"
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "ble_registered_devices": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/BleRegisteredDevice"
                    }
                },
                "devices": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Device"
                    }
                }
            },
            "required": [
                "ble_registered_devices",
                "created_at",
                "devices",
                "id",
                "schema_version",
                "tags",
                "updated_at"
            ],
            "title": "Welcome4"
        },
        "BleRegisteredDevice": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "name": {
                    "type": "string"
                },
                "services": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "description": {
                    "type": "string"
                }
            },
            "required": [
                "description",
                "name",
                "services"
            ],
            "title": "BleRegisteredDevice"
        },
        "Device": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "name": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "ble": {
                    "$ref": "#/definitions/DeviceBle"
                },
                "global_config_values": {
                    "type": "array",
                    "items": {}
                },
                "data_streams": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/DataStream"
                    }
                }
            },
            "required": [
                "ble",
                "data_streams",
                "description",
                "global_config_values",
                "name",
                "tags"
            ],
            "title": "Device"
        },
        "DeviceBle": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "ble_registered_services": {
                    "type": "array",
                    "items": {}
                },
                "info_service_uuid": {
                    "type": "string",
                    "format": "uuid"
                },
                "epoch_char_uuid": {
                    "type": "string",
                    "format": "uuid"
                }
            },
            "required": [
                "ble_registered_services",
                "epoch_char_uuid",
                "info_service_uuid"
            ],
            "title": "DeviceBle"
        },
        "DataStream": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "include_anchor_timestamp": {
                    "type": "boolean"
                },
                "offset_data_value": {
                    "$ref": "#/definitions/DataValue"
                },
                "config_values": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/ConfigValue"
                    }
                },
                "data_values": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/DataValue"
                    }
                },
                "ble": {
                    "$ref": "#/definitions/DataStreamBle"
                }
            },
            "required": [
                "ble",
                "config_values",
                "data_values",
                "description",
                "id",
                "include_anchor_timestamp",
                "name",
                "offset_data_value"
            ],
            "title": "DataStream"
        },
        "DataStreamBle": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "service_uuid": {
                    "type": "string",
                    "format": "uuid"
                },
                "data_char_uuid": {
                    "type": "string",
                    "format": "uuid"
                },
                "config_char_uuid": {
                    "type": "string",
                    "format": "uuid"
                }
            },
            "required": [
                "config_char_uuid",
                "data_char_uuid",
                "service_uuid"
            ],
            "title": "DataStreamBle"
        },
        "ConfigValue": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "name": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "byte_start": {
                    "type": "integer"
                },
                "byte_end": {
                    "type": "integer"
                },
                "size": {
                    "type": "integer"
                },
                "unit": {
                    "anyOf": [
                        {
                            "type": "null"
                        },
                        {
                            "type": "string"
                        }
                    ]
                },
                "type": {
                    "$ref": "#/definitions/Type"
                },
                "default_value": {
                    "type": "string",
                    "format": "integer"
                },
                "options": {
                    "anyOf": [
                        {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/Option"
                            }
                        },
                        {
                            "type": "null"
                        }
                    ]
                },
                "range": {
                    "anyOf": [
                        {
                            "$ref": "#/definitions/Range"
                        },
                        {
                            "type": "null"
                        }
                    ]
                }
            },
            "required": [
                "byte_end",
                "byte_start",
                "default_value",
                "description",
                "name",
                "options",
                "range",
                "size",
                "type",
                "unit"
            ],
            "title": "ConfigValue"
        },
        "Option": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "name": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "value": {
                    "type": "string",
                    "format": "integer"
                }
            },
            "required": [
                "description",
                "name",
                "value"
            ],
            "title": "Option"
        },
        "Range": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "start": {
                    "type": "integer"
                },
                "end": {
                    "type": "integer"
                },
                "step": {
                    "type": "integer"
                }
            },
            "required": [
                "end",
                "start",
                "step"
            ],
            "title": "Range"
        },
        "DataValue": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "name": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "unit": {
                    "$ref": "#/definitions/Unit"
                },
                "byte_start": {
                    "type": "integer"
                },
                "byte_end": {
                    "type": "integer"
                },
                "size": {
                    "type": "integer"
                },
                "type": {
                    "$ref": "#/definitions/Type"
                },
                "multiplier": {
                    "anyOf": [
                        {
                            "type": "number"
                        },
                        {
                            "type": "null"
                        }
                    ]
                },
                "variable_type": {
                    "type": "string"
                },
                "depends_on": {
                    "type": "null"
                }
            },
            "required": [
                "byte_end",
                "byte_start",
                "description",
                "multiplier",
                "name",
                "size",
                "type",
                "unit"
            ],
            "title": "DataValue"
        },
        "Type": {
            "type": "string",
            "enum": [
                "int",
                "uint"
            ],
            "title": "Type"
        },
        "Unit": {
            "type": "string",
            "enum": [
                "",
                "arb",
                "ms"
            ],
            "title": "Unit"
        }
    }
}

=== Flexi-BLE/InterfaceModel/sample.json
{
    "id": "flexiBLE-sample-spec",
    "schema_version": "0.3",
    "created_at": "2022-09-14T00:00:00.000Z",
    "updated_at": "2022-09-14T00:00:00.000Z",
    "tags": [
        "development"
    ],
    "ble_registered_devices": [
        {
            "name": "Polar H10 821A5D29",
            "services": [
                "heart-rate",
                "battery"
            ],
            "description": "a polar heart rate monitor for ground truth data collection"
        }
    ],
    "devices": [
        {
            "name": "FlexiBLE-pre-alpha",
            "description": "a locally stored file for nrf5340 device config",
            "tags": [
                "research"
            ],
            "ble": {
                "ble_registered_services": [],
                "info_service_uuid": "1a220001-c2ed-4d11-ad1e-fc06d8a02d37",
                "epoch_char_uuid": "1a220002-c2ed-4d11-ad1e-fc06d8a02d37"
            },
            "global_config_values": [],
            "data_streams": [
                {
                    "id": "0xb92c",
                    "name": "accelerometry",
                    "description": "Accelerometer sensor (x, y, z axis)",
                    "include_anchor_timestamp": true,
                    "offset_data_value": {
                        "name": "ms_offset",
                        "description": "relative time since the previous reading",
                        "unit": "ms",
                        "byte_start": 12,
                        "byte_end": 13,
                        "size": 1,
                        "type": "uint",
                        "multiplier": null,
                        "variable_type": "none"
                    },
                    "config_values": [
                        {
                            "name": "sensor_state",
                            "description": "state of the accelerometer sensor",
                            "byte_start": 0,
                            "byte_end": 1,
                            "size": 1,
                            "unit": null,
                            "type": "uint",
                            "default_value": "0",
                            "options": [
                                {
                                    "name": "disabled",
                                    "description": "the sensor will not stream data",
                                    "value": "0"
                                },
                                {
                                    "name": "streaming",
                                    "description": "the sensor will stream data",
                                    "value": "1"
                                }
                            ],
                            "range": null
                        },
                        {
                            "name": "desired_frequency",
                            "description": "the desired frequency of the sensor",
                            "byte_start": 1,
                            "byte_end": 3,
                            "size": 2,
                            "type": "uint",
                            "unit": "Hz",
                            "options": null,
                            "default_value": "10",
                            "range": {
                                "start": 20,
                                "end": 500,
                                "step": 20
                            }
                        },
                        {
                            "name": "batch_size",
                            "description": "the maximun size of payload",
                            "byte_start": 3,
                            "byte_end": 4,
                            "size": 1,
                            "type": "uint",
                            "unit": "bytes",
                            "options": null,
                            "default_value": "240",
                            "range": {
                                "start": 0,
                                "end": 240,
                                "step": 10
                            }
                        }
                    ],
                    "data_values": [
                        {
                            "name": "accel_x",
                            "description": "x-axis value",
                            "unit": "",
                            "byte_start": 0,
                            "byte_end": 4,
                            "size": 4,
                            "type": "int",
                            "multiplier": 0.000001,
                            "variable_type": "value",
                            "depends_on": null
                        },
                        {
                            "name": "accel_y",
                            "description": "y-axis value",
                            "unit": "",
                            "byte_start": 4,
                            "byte_end": 8,
                            "size": 4,
                            "type": "int",
                            "multiplier": 0.000001,
                            "variable_type": "value",
                            "depends_on": null
                        },
                        {
                            "name": "accel_z",
                            "description": "z-axis value",
                            "unit": "",
                            "byte_start": 8,
                            "byte_end": 12,
                            "size": 4,
                            "type": "int",
                            "multiplier": 0.000001,
                            "variable_type": "value",
                            "depends_on": null
                        }
                    ],
                    "ble": {
                        "service_uuid": "1a220003-c2ed-4d11-ad1e-fc06d8a02d37",
                        "data_char_uuid": "1a220005-c2ed-4d11-ad1e-fc06d8a02d37",
                        "config_char_uuid": "1a220004-c2ed-4d11-ad1e-fc06d8a02d37"
                    }
                },
                {
                    "id": "0xb94d",
                    "name": "random-number",
                    "description": "random number data stream to simulate a sensor, used for throughput testing",
                    "include_anchor_timestamp": true,
                    "offset_data_value": {
                        "name": "ms_offset",
                        "description": "relative time since the previous reading",
                        "unit": "ms",
                        "byte_start": 20,
                        "byte_end": 21,
                        "size": 1,
                        "type": "uint",
                        "multiplier": null,
                        "variable_type": "none"
                    },
                    "config_values": [
                        {
                            "name": "sensor_state",
                            "description": "state of the accelerometer sensor",
                            "byte_start": 0,
                            "byte_end": 1,
                            "size": 1,
                            "unit": null,
                            "type": "uint",
                            "default_value": "0",
                            "options": [
                                {
                                    "name": "disabled",
                                    "description": "the sensor will not stream data",
                                    "value": "0"
                                },
                                {
                                    "name": "streaming",
                                    "description": "the sensor will stream data",
                                    "value": "1"
                                }
                            ],
                            "range": null
                        },
                        {
                            "name": "desired_frequency",
                            "description": "the desired frequency of the sensor",
                            "byte_start": 1,
                            "byte_end": 3,
                            "size": 2,
                            "type": "uint",
                            "unit": "Hz",
                            "options": null,
                            "default_value":  "100",
                            "range": {
                                "start": 0,
                                "end": 1000,
                                "step": 50
                            }
                        }
                    ],
                    "data_values": [
                        {
                            "name": "value1",
                            "description": "random value #1",
                            "unit": "arb",
                            "byte_start": 0,
                            "byte_end": 2,
                            "size": 2,
                            "type": "uint",
                            "multiplier": null,
                            "variable_type": "value",
                            "depends_on": null
                        },
                        {
                            "name": "value2",
                            "description": "random value #2",
                            "unit": "arb",
                            "byte_start": 2,
                            "byte_end": 4,
                            "size": 2,
                            "type": "uint",
                            "multiplier": null,
                            "variable_type": "value",
                            "depends_on": null
                        },
                        {
                            "name": "value3",
                            "description": "random value #3",
